# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 08:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrib_date', models.DateTimeField(verbose_name='Fund Contribution Date')),
                ('contrib_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Contributed Amount $')),
                ('contrib_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
