# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Booking Date')),
                ('rate', models.DecimalField(decimal_places=2, default='4.0', max_digits=12, verbose_name='Booking Rate/Hour')),
                ('hour', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Booking Hour')),
                ('court', models.CharField(choices=[('1', 'Court 1'), ('2', 'Court 2'), ('3', 'Court 3'), ('4', 'Court 4'), ('5', 'Court 5'), ('6', 'Court 6')], max_length=2, verbose_name='Court Number')),
                ('location', models.CharField(default='Republic Poly', max_length=100, verbose_name='Location')),
            ],
        ),
    ]
