# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hour',
            field=models.CharField(choices=[('0', '12:00 AM'), ('1', '01:00 AM'), ('2', '02:00 AM'), ('3', '03:00 AM'), ('4', '04:00 AM'), ('5', '05:00 AM'), ('6', '06:00 AM'), ('7', '07:00 AM'), ('8', '08:00 AM'), ('9', '09:00 AM'), ('10', '10:00 AM'), ('11', '11:00 AM'), ('12', '12:00 PM'), ('13', '01:00 PM'), ('14', '02:00 PM'), ('15', '03:00 PM'), ('16', '04:00 PM'), ('17', '05:00 PM'), ('18', '06:00 PM'), ('19', '07:00 PM'), ('20', '08:00 PM'), ('21', '09:00 PM'), ('22', '10:00 PM'), ('23', '11:00 PM')], max_length=8, verbose_name='Booking Hour'),
        ),
    ]
