# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20160708_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hour',
            field=models.IntegerField(default=3, verbose_name='No. Of Hours'),
        ),
    ]
