# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20160708_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Valid Booking'),
        ),
    ]
